### ISSUE TITLE
Context File structure

### ISSUE THREAD

**Issue by mattia6690** [Open-EO/openeo-udf-python-to-r#15] opened 2022-06-23 14:15 UTC
During today's test we noticed that the `context` parameter is rather difficult to use in it's current implementation.

- The parameter appears to work only in `reduce_dimension` when multiple chunks are being addressed
- The parameter does not work with `apply`
- The context does not allow strings, right? This would be a great addition to hand the url location of the model to the UDF

**Comment by m-mohr** [comment] 2022-06-24 19:20
run_udf only allows objects to be passed, at least that's what the schema says right now. Will check....

**Comment by m-mohr** [comment] 2022-06-29 14:10
Can you provide an example, please?

**Comment by m-mohr** [comment] 2022-07-01 11:21
As @mattia6690 is "gone" and I can't reproduce it right now, I'm closing this.

**Closed by m-mohr** 2022-07-01 11:21 UTC
